// Generated by https://quicktype.io

export interface Usuarios {
    id?:                   string;
    usuario:               string;
    contrasena:            string;
    nombre:                string;
    apellido:              string;
    telefono:              string;
    id_rol?:                string;
    fecha_creacion:        string;
    usuario_creacion:      string;
    fecha_actualizacion?:   string;
    usuario_actualizacion?: string;
    estado:                string;
}
